### ISSUE TITLE
Enhancement: Upgrade to sass-lint 1.10

### ISSUE THREAD

**Issue by Listor** [brackets-userland/brackets-sass-lint#4]
The new sass-lint has support to enbable / disable linter rules. It would be super awesome if this extension could support it as well.

https://github.com/sasstools/sass-lint/releases/tag/1.10

**Comment by petetnt** [comment]
👍  cool! I'll see what I can do as soon as I have the time, but PRs are always welcome too!

**Comment by petetnt** [comment]
Hi @Listor, I just updated the dep to `1.10` and it seems to be working great! 

https://www.npmjs.com/package/brackets-sass-lint

You should see the update in Brackets NPM registry shortly!

**Comment by Listor** [comment]
wow thx a lot ! :) that was fast ;) 👍
